# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления из-под user1
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token efb9659cabd4feaeac7cfa0a8940d5d17c6a6a17

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# создание объявления из-под user2
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b103a6f5c1bfcc93da3626aee71e9d08fd50a311

{
  "title": "Шкаф IKEA2",
  "description": "Срочно2",
  "status": "CLOSED"
}

###

# попытка поменять объявление из-под user1
PATCH {{baseUrl}}/advertisements/34/
Content-Type: application/json
Authorization: Token efb9659cabd4feaeac7cfa0a8940d5d17c6a6a17

{
  "status": "CLOSED"
}

###

# попытка удалить объявление из-под user1
DELETE {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token efb9659cabd4feaeac7cfa0a8940d5d17c6a6a17

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2022-05-11
Content-Type: application/json

###

# фильтрация по статусу OPEN c сортировкой
GET {{baseUrl}}/advertisements/?status=OPEN&ordering=id
Content-Type: application/json

###

# фильтрация по статусу CLOSED
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json