# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления user1
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 99a5cf504590344a5bd1dbc8f590dacef30076bd

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# создание объявления user2
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 9da5c358d81f7846b9cfd626978e48010915f6f8
9da5c358d81f7846b9cfd626978e48010915f6f8
{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 99a5cf504590344a5bd1dbc8f590dacef30076bd

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
