# Generated by Django 4.0.1 on 2022-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_artilescope_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtileScope',
            new_name='ArticleScope',
        ),
        migrations.RemoveConstraint(
            model_name='articlescope',
            name='ArticleScopeWhithoutDoubles',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleScope', to='articles.Tag'),
        ),
    ]
