# Generated by Django 4.0.1 on 2022-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_artilescope_articlescope_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlescope',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='ArticleScopeWhithoutDoubles'),
        ),
    ]
